Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/mpi4py-3.0.3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/mpi4py-3.0.3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/davidyangnyc/.local/lib/python3.7/site-packages/mpi4py/futures/__main__.py", line 72, in <module>
    main()
  File "/home/davidyangnyc/.local/lib/python3.7/site-packages/mpi4py/futures/__main__.py", line 60, in main
    run_command_line()
  File "/home/davidyangnyc/.local/lib/python3.7/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/mpi4py-3.0.3/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/mpi4py-3.0.3/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/mpi4py-3.0.3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "PTSD_cognet.py", line 7, in <module>
    qnet=load_qnet('examples_results/PTSD_cognet_test.joblib')
  File "/home/davidyangnyc/.local/lib/python3.7/site-packages/quasinet/qnet.py", line 680, in load_qnet
    qnet = load(f)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/mpi4py-3.0.3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 577, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'examples_results/PTSD_cognet_test.joblib'
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
