Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/davidyangnyc/.local/lib/python3.7/site-packages/mpi4py/futures/__main__.py", line 72, in <module>
    main()
  File "/home/davidyangnyc/.local/lib/python3.7/site-packages/mpi4py/futures/__main__.py", line 60, in main
    run_command_line()
  File "/home/davidyangnyc/.local/lib/python3.7/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "PTSD_cognet.py", line 28, in <module>
    result = pd.DataFrame(result)
  File "/home/davidyangnyc/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 502, in __init__
    data = list(data)
  File "/home/davidyangnyc/.local/lib/python3.7/site-packages/mpi4py/futures/pool.py", line 207, in result_iterator
    yield futures.pop().result()
  File "/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
AttributeError: 'numpy.ndarray' object has no attribute 'iloc'
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
